name: Pub Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.0"
          channel: stable
          cache: true

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: 🔐 Add Pub Token
        run: echo ${{ secrets.CLOUDSMITHAPIKEY }} | dart pub token add https://dart.cloudsmith.io/digizorg/default/

      - name: 🌵 Dry Run
        run: flutter pub publish --dry-run

      - name: 📢 Publish
        run: flutter pub publish -f
